sudo: false
language: ruby

rvm:
  - 2.2.10
  - 2.3.8
  - 2.4.5
  - 2.5.3

gemfile:
  - letter_opener_web_5_0.gemfile
  - letter_opener_web_5_1.gemfile
  - letter_opener_web_5_2.gemfile

notifications:
  email: false

deploy:
  provider: rubygems
  gem: letter_opener_web
  api_key:
    secure: Rv1IgeIhnfIV9NVr3iPwb2UCXe0UEtuZHfgkGruu3yvfoSGmQQ0xnc45ZhOH8ANl6tjzYNuilSDYbhz3fWOmniHsnzLGbFbccz/CWHmldUpPgVnKQ0d0Bm2EeNuVpmHwdnG7KEqMC0x1gxFYks62BGpx4C/2Kh5nWbvvPxN8X0U=
  on:
    tags: true
    repo: fgrehm/letter_opener_web
